apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ctphybridcloudowner
  namespace: ctphybrid
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - set
  - watch
  - list